name: Deploy to Staging

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Deploy to staging repo
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.STAGING_DEPLOY_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'entethalliance'
          destination-repository-name: 'wg-privacy-staging'
          target-branch: main
          commit-message: 'Staging deploy from ${{ github.repository }}@${{ github.sha }}'
